type OrderInputObjectWithRating {
  order: OrderInputObject
  rating: Float
}

input QuoteInputObject {
  quote: Quote
}

extend type Query {
  uuid: ID
  leaseTypes: JSON
  sortOrder: JSON
  lastStep: JSON
  isSessionFinished: Boolean
  storedPerson: PersonType
  storedPersonUuid: ID
  storedOrder: OrderInputObjectWithRating
  storedPersonEmail: String
  storedQuote: Quote
}

extend type Mutation {
  savePerson(person: PersonInputObject): PersonType
  savePersonUuid(uuid: ID): ID
  saveOrder(order: OrderInputObject, rating: Float): OrderInputObjectWithRating
  savePersonEmail(email: String): String
  saveQuote(input: QuoteInputObject): Quote
}
