extend type Query {
  uuid: ID
  leaseTypes: JSON
  sortOrder: JSON
  lastStep: JSON
  isSessionFinished: Boolean
  storedPerson: PersonType
  storedPersonUuid: ID
}

extend type Mutation {
  savePerson(person: PersonInputObject): PersonType
  savePersonUuid(uuid: ID): ID
}
