name: nsf-build-workflow

env:
  APP: next-storefront
  ENV: dev
  STACK: grid
  ECR_REGION: eu-west-2
  BUILD_ENV_EXEC_S3_PATH: https://build-env-var.s3.eu-west-2.amazonaws.com/build-env-var.linux-amd64

on:
  workflow_dispatch:
    inputs:
      env:
        type: string
        required: true
      tag:
        type: string
        required: true
      github_sha:
        type: string
        required: true

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true      

jobs:
  set-env:
    runs-on: ubuntu-latest
    outputs:
      github_actions_role_secret: ${{ steps.variables.outputs.github_actions_role_secret }}
    steps:
      - id: variables
        run: |
          env_upper=$(echo ${{ github.event.inputs.env }} | tr '[:lower:]' '[:upper:]')
          env_upper=${env_upper//-/_}
          github_actions_role_secret="GRID_${env_upper}_GHA_ACTION_ROLE"
          echo "::set-output name=github_actions_role_secret::${github_actions_role_secret}"

  init:
    runs-on: ubuntu-latest
    needs: [set-env]

    # These permissions are required to use Github OIDC.
    permissions:
      id-token: write
      contents: read    

    steps:
      # Uses OIDC to assume the role in AWS rather than maintaining AWS credentials 
      # in Github. There is a corresponding OIDC provider in IAM setup to receive tokens
      # from Github. See https://github.com/aws-actions/configure-aws-credentials#assuming-a-role
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.ECR_REGION }}
          role-to-assume: ${{ secrets[needs.set-env.outputs.github_actions_role_secret] }}
      - uses: aws-actions/amazon-ecr-login@v1
      - name: Create repository if not exists
        if: ${{ github.event.inputs.force_rebuild != 'true' }}
        run: aws ecr describe-repositories --repository-names ${{ env.APP }} --region ${{ env.ECR_REGION }} || aws ecr create-repository --repository-name ${{ env.APP }} --region ${{ env.ECR_REGION }}

  package:
    runs-on: ubuntu-latest
    needs: [init, set-env]

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.github_sha }}
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.ECR_REGION }}
          role-to-assume: ${{ secrets[needs.set-env.outputs.github_actions_role_secret] }}
      - name: Curl build-env-var
        run: |
          curl ${{ env.BUILD_ENV_EXEC_S3_PATH }} --output build-env-var.linux-amd64
          chmod +x build-env-var.linux-amd64
      - uses: aws-actions/amazon-ecr-login@v1
      - name: Pull latest develop image for cache
        run: docker pull ${{ secrets.GRID_PROD_REPO_PREFIX }}/${{ env.APP }}:latest || true
      - name: Docker build
        run: |
          ARTEFACT_TAG=${{ github.event.inputs.tag }}
          eval "$(./build-env-var.linux-amd64 -ignoreMissing -ssmPrefix=/${{ github.event.inputs.env }}/${{ env.STACK }}/${{ env.APP }} -envTemplate=env.template -envStdout)"
          docker build -t ${{ secrets.GRID_PROD_REPO_PREFIX }}/${{ env.APP }}:${ARTEFACT_TAG} \
          --build-arg NPM_TOKEN=${{ secrets.GRID_NPM_TOKEN }} \
          --build-arg PRERENDER_SERVICE_URL=${PRERENDER_SERVICE_URL} \
          --build-arg API_KEY=${API_KEY} \
          --build-arg API_URL=${API_URL} \
          --build-arg ENV=${ENV} \
          --build-arg GTM_ID=${GTM_ID} \
          --build-arg HEAP_ID=${HEAP_ID} \
          --build-arg MICROBLINK_URL=${MICROBLINK_URL} \
          --build-arg IMG_OPTIMISATION_HOST=${IMG_OPTIMISATION_HOST} \
          --build-arg LOQATE_KEY=${LOQATE_KEY} \
          --build-arg NODE_ENV=${NODE_ENV} \
          --build-arg HOST_DOMAIN=${HOST_DOMAIN} \
          --build-arg SEO_BUCKET_NAME=${SEO_BUCKET_NAME} \
          --cache-from ${{ secrets.GRID_PROD_REPO_PREFIX }}/${{ env.APP }}:latest .
      - name: Docker push
        run: |
          ARTEFACT_TAG=${{ steps.create-tag.outputs.tag }}
          docker push ${{ secrets.GRID_PROD_REPO_PREFIX }}/${{ env.APP }}:${ARTEFACT_TAG}
          echo "Pushed image ${ARTEFACT_TAG}"
